"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Basic settings
# =========================

SECRET_KEY = "django-insecure-(x9v!(8ql6r6d*-fyp03@-_k5-*(h(z**!0$hi))cm+bv-orj@"
DEBUG = True
ALLOWED_HOSTS = ["*"]

#
# =========================
# Remote media proxy (HTTPS mixed content fix)
# =========================
#
# 远程图片仍是 HTTP 服务，但页面可能跑在 HTTPS 下会被浏览器拦截；
# 统一通过本项目同源接口 `/media-proxy/<path>` 转发。
#
# 只使用一个变量：直接填写 `http(s)://ip:port`
REMOTE_MEDIA_BASE = "http://116.62.214.146:8175"


# =========================
# Application definition
# =========================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework.authtoken",

    "storageSystem",
    "screen",  # screen
    "labDataset",  # 实验室数据集管理
]


# 开发环境可选：django-sslserver（用于 runsslserver 快速 HTTPS）
try:
    import sslserver  # noqa: F401
except Exception:
    sslserver = None
else:
    INSTALLED_APPS.insert(-1, "sslserver")


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"  # 允许同源网站嵌入

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "aiModels", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# =========================
# Database
# =========================
def _db_setting(env_key: str, default):
    """启动器通过环境变量注入数据库配置。"""
    value = os.environ.get(env_key)
    return default if value is None or value == "" else value


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
        'NAME': _db_setting("DB_NAME", "web_database"), # 数据库名称
        'HOST': _db_setting("DB_HOST", "127.0.0.1"), # 数据库地址，本机 ip 地址 127.0.0.1
        'PORT': int(_db_setting("DB_PORT", "3306")), # 端口
        'USER': _db_setting("DB_USER", "root"),  # 数据库用户名root
        'PASSWORD': _db_setting("DB_PASSWORD", ""), # 数据库密码
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },

    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',    # 数据库引擎
    #     'NAME': "coldchain", # 数据库名称
    #     'HOST': "47.113.147.210", # 数据库地址，
    #     'PORT': 3306, # 端口
    #     'USER': "jetbot",  # 数据库用户名
    #     'PASSWORD': "yahboom", # 数据库密码
    #     'OPTIONS': {
    #         'charset': 'utf8mb4',
    #     },
    # },

    # 远程 MySQL 数据库：pig（冷库环境）
    "pig": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": _db_setting("PIG_NAME", "pig"),
        "HOST": _db_setting("PIG_HOST", "116.62.214.146"),
        "PORT": int(_db_setting("PIG_PORT", "3306")),
        "USER": _db_setting("PIG_USER", "wyh22"),
        "PASSWORD": _db_setting("PIG_PASSWORD", "wyh123456"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    },
}

# storageSystem/views/api_dashboard.py 使用此配置连接数据库
# 复用 DATABASES['default'] 的配置
REMOTE_MYSQL = {
    "HOST": DATABASES['default']['HOST'],
    "PORT": int(DATABASES['default']['PORT']),
    "USER": DATABASES['default']['USER'],
    "PASSWORD": DATABASES['default']['PASSWORD'],
    "NAME": DATABASES['default']['NAME'],
    "CHARSET": DATABASES['default'].get('OPTIONS', {}).get('charset', 'utf8mb4'),
}


# Password validation
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# Internationalization
# =========================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True


# =========================
# Static & Media
# =========================

# ✅ 静态资源（只保留一个，避免你之前重复定义导致路径混乱）
STATIC_URL = "/static/"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# =========================
# Default primary key field type
# =========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# Django REST framework
# =========================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
}

