# Generated by Django 5.2.10 on 2026-01-22 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='冷库名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='冷库编号')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址/场地')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '冷库',
                'verbose_name_plural': '冷库',
                'db_table': 'coldroom',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='设备名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='设备编号')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='位置信息')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('alarm', '告警')], db_index=True, default='offline', max_length=16, verbose_name='在线状态')),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后上报时间')),
                ('device_type', models.CharField(blank=True, default='', max_length=32, verbose_name='设备类型')),
                ('vendor', models.CharField(blank=True, default='', max_length=64, verbose_name='厂商')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='storageSystem.coldroom', verbose_name='所属冷库')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', '提示'), ('warning', '告警'), ('critical', '严重')], db_index=True, default='warning', max_length=16, verbose_name='告警级别')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='告警内容')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否未处理')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='storageSystem.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'db_table': 'alarm',
            },
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_at', models.DateTimeField(db_index=True, verbose_name='上报时间')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='温度')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='湿度')),
                ('battery', models.FloatField(blank=True, null=True, verbose_name='电量')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='storageSystem.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备上报',
                'verbose_name_plural': '设备上报',
                'db_table': 'device_reading',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['cold_room', 'status'], name='device_cold_ro_0d290d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['code'], name='device_code_7fb501_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['is_active', 'level'], name='alarm_is_acti_d5662a_idx'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['device', 'occurred_at'], name='alarm_device__8bcf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['device', 'reported_at'], name='device_read_device__0ee7f3_idx'),
        ),
    ]
